name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        git submodule update --init
        cargo build --verbose
    - name: Check Format
      run: cargo fmt -- --check
    - name: Run Tests
      run: cargo test -p misfire
      
